version: '3'  # version of compose format 

services:
  web:
    build: .
    ports:
      - 6285:80
    volumes:
      - .:/todo
    links:
      - db

  #laptop-service:
  #build: ./laptop  
  #volumes:
  #- ./laptop:/usr/src/app 
  #ports:
  #- 6285:80 # host:container
  db:
          image: mongo:3

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 6284:80  # host:container
    depends_on:
      - web  # website is not going to work unless laptop-service is running
